version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: apigame-docker-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=A123456
        - MYSQL_DATABASE=apigamedb
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=A123456
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: apigame-docker-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: apigame-docker-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini