version: "3"
services:
    laravel-app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./:/usr/share/nginx
        networks: 
            - app-network
    mysql-app:
        image: mysql:5.7
        container_name: mysql-apigame
        working_dir: /application
        volumes:
        - .:/application
        environment:
        - MYSQL_ROOT_PASSWORD=A123456
        - MYSQL_DATABASE=apigamedb
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=A123456
        ports:
        - "3308:3308"
        networks: 
            - app-network
networks:
    app-network:
        driver: bridge