version: "3"
services:
    laravel-app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./:/usr/share/nginx
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
