version: "3"
services:
    laravel-app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./:/usr/share/nginx
    mysql:
        image: mysql:5.7
        container_name: mysql-apigame
        working_dir: /application
        volumes:
        - .:/application
        environment:
        - MYSQL_ROOT_PASSWORD=adminroot
        - MYSQL_DATABASE=apigamedb
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
        ports:
        - "3308:3306"